version: "3"

services:
  db:
      image: postgres 
      restart: always
      ports:
          - "5432:5432"
      environment:
          POSTGRES_USER: pong
          POSTGRES_PASSWORD: pong
          POSTGRES_DB: pongdb

#docker-compose up -d